services:
  webapp-prod:
    container_name: webapp-prod
    build:
      context: ./webapp
      dockerfile: /docker/prod.Dockerfile
      args:
        TEST_VAR: ${TEST_VAR}
        SECRET_VAR: ${SECRET_VAR}
    restart: always
    ports:
      - 3000:3000

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      TZ: Europe/Bucharest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
