services:
  webapp-dev:
    container_name: webapp-dev
    build:
      context: ./webapp
      dockerfile: /docker/dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      TEST_VAR: ${TEST_VAR}
      SECRET_VAR: ${SECRET_VAR}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
      NEXT_PUBLIC_DEFAULT_REGISTER_PASSWORD: ${NEXT_PUBLIC_DEFAULT_REGISTER_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}

    # Set environment variables based on the .env file
    # env_file:
    #   - .env
    restart: always
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./webapp/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Bucharest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
